// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.jsx";
import * as $$0 from "./islands/FeedOptions.jsx";
import * as $$1 from "./islands/Recommended.jsx";

const manifest = {
  routes: {
    "./routes/index.jsx": $0,
  },
  islands: {
    "./islands/FeedOptions.jsx": $$0,
    "./islands/Recommended.jsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
